### ISSUE TITLE
geen code??

### ISSUE THREAD

**Issue by stgm** [ewoudhermans/GPSTourGuide#2]
Graag uitleg hierover :-)
Vandaag geen code online == niet meer meedoen

close deze issue als je het begrepen/gefixt hebt

**Comment by ewoudhermans** [comment]
Beste Martijn, sorry dat ik het er zo laat heb opgezet. het staat er nu bij. Ik heb er alleen per ongeluk een verkeerde bij gezet. De goede code is TourGuide en niet GPSTourGuide.
